# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ main ]
    paths: 
        - "dotnet/**"
  pull_request:
    branches: [ main ]
    paths: 
        - "dotnet/**"

  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./dotnet
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
         versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-quality: 'ga'

    - name: Restore dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --no-restore /p:AssemblyVersion=${{ env.GitVersion_AssemblySemVer }} 
    - name: Test
      working-directory: ${{env.working-directory}}
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true --collect:"XPlat Code Coverage"

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.23
      with:
        reports: /dotnet/tests/starter-api-tests/TestResults/*/coverage.cobertura.xml
        targetdir: coveragereport
        reporttypes: Cobertura;XML;MarkdownSummaryGithub