# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'react-app/**'
  pull_request:
    branches: [main]
    paths:
      - 'react-app/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: react-app/
    env:
      VERSION: if github.event == 'pull request' && '${github.ref_number}' | 'latest' 
    steps:
    # check out
    - uses: actions/checkout@v3
    # setup node
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json' 
    # npm install    
    - run: npm ci
    # npm build
    - run: npm run build --if-present
    # npm test
    - run: npm test
    # setup QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    #setup Docker buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # docker hub login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # docker build and push
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{vars.DOCKERHUB_REPOSITORY }}:${{env.VERSION}}