name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 # push:
  #  branches: [ "main" ]
  push:
    branches: [feature/release-management]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  create-pre-release:
    name: Create pre Release
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
    
    - name: Create Release
      run: |
        gh release create ${{env.GitVersion_MajorMinorPatch}} -t 'Release ${{env.GitVersion_MajorMinorPatch}}' --target ${{github.ref}}  --p

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: create-pre-release
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
    
    - name: Create Release
      run: |
        gh release create ${{env.GitVersion_MajorMinorPatch}} -t 'Release ${{env.GitVersion_MajorMinorPatch}}' --target ${{github.ref}}  --generate-notes


