# both jobs uses Github CLI to create and edit a release. 
# more info here https://cli.github.com/manual/gh_release
name: Release from tag

# Controls when the workflow will run
on:
  push:
    branches: ["feature/create-release-from-tag"]
    tags:
      - rc.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  TAG_PREFIX: v # tag pre fix name can be changed 
    
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
    
    - name: Create Release
      run: |
        gh release edit ${{github.ref_name}} -t 'Release ${{env.TAG_PREFIX}}.${{env.GitVersion_MajorMinorPatch}}' --target ${{github.ref}}


