name: Git Version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This gets the Semantic Version
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
         versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
      - name: Create Tag
        run: |
         git tag rc.${{ env.semVer }}
         git push origin rc.${{ env.semVer }}
  # # This creates a tag
  # create-tag:
  #   name: Create Tag from Semantic Version
  #   runs-on: ubuntu-latest
  #   needs: calculate-version
  #   env:
  #     SEMVER: ${{ needs.calculate-version.outputs.semVer }}
  #   # GH_TOKEN: ${{ github.token }}
  #   steps:
  #     - name: Create Tag
  #       run: |
  #        git tag rc.${{ env.SEMVER }}
  #        git push origin rc.${{ env.SEMVER }}


